manifest-version = 1

[component]
name = "axeptio"
version = "1.0.0"

category = "consent-management"
subcategory = "consent-mapping"
description = '''
Axeptio Consent Mapping lets you forward the user consent managed by Axeptio CMP with all your other components.
You no longer need to specify your users' consent via the sdk or Edgee data layer, everything is done automatically.
'''
documentation = "https://www.edgee.cloud/docs/components/cmp/axeptio-consent-mapping"
repository = "https://github.com/edgee-cloud/axeptio-component"
language = "Rust"
wit-version = "1.0.0"

[component.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target && (mv ./target/wasm32-wasip2/release/example_rust_component.wasm ./component.wasm || true)"
output_path = "component.wasm"
