manifest-version = 1

[component]
name = "axeptio"
version = "1.0.0"

category = "consent-management"
subcategory = "consent-mapping"
description = "Example Rust component for consent-mapping"
documentation = "https://github.com/edgee-cloud/axeptio-component"
repository = "https://github.com/edgee-cloud/axeptio-component"
language = "Rust"
wit-version = "1.0.0"

[component.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target && (mv ./target/wasm32-wasip2/release/example_rust_component.wasm ./component.wasm || true)"
output_path = "component.wasm"
